### ISSUE TITLE
Folder /home

### ISSUE THREAD

**Issue by LutzHas** [corbinlc/GNURootDebian#130]
I use the App for quite a long time. Full five Stars without hesitation.
After the last bug fix release one problem remains for me.

In the former version the folders /home in GnuRoot Debian and the folder /storage/emulated/0/GNURoot/home in Android were identical. So there was no problem to copy files to the GnuRoot Debian file system.

Now these two folders are completely independent.
Two complete new installations didn't change that.

Mainly i use GnuRoot Debian to compile tex-files with ConTeXt to PDFs and send them by WhatsApp.
That is now a difficult task for me.

Is there a new way to exchage file between the App and Android?

**Comment by corbinlc** [comment]
This is a bug.  It should behave the way it did before.  Thank you for reporting the issue!  You are the first to do so.  It should be easy to fix.  I know the change that probably caused the issue.

**Comment by corbinlc** [comment]
Btw, from inside GNURoot Debian, /sdcard should point you at your sdcard or /storage/emulated/0/ in your case.  That is just a work around for now.

**Comment by LutzHas** [comment]
Hi Corbin,

this works very fine for me. I should that have find out myself.
Thank you very much for your work on this App. It is VERY helpful to me.

**Comment by corbinlc** [comment]
Does the /home directory work fine for you on todays version?

**Comment by LutzHas** [comment]
Yes, all works as expected again, Thank you very much.

**Comment by peasthope** [comment]
Another problem with /home.  Another symptom of the bug discussed 
above?

In the system settings here, the default write disk is set to "SD 
card". There is a folder named home in the external microSD card. In 
the menu under Preferences, "HOME folder" is chosen and set to 
"storage/sdcard1/home/".  This is ineffective.  The home folder is not 
in the external card.  Should this work?

Thanks,                       ... Peter E.

**Comment by corbinlc** [comment]
That setting does not work.  It is a carry over from us copying code from the Android Terminal Emulator.  You home directory is on the sdcard, but is at /sdcard/GNURoot/home if looking for it from a file explorer/browser.  Do you see the home directory there?

**Comment by peasthope** [comment]
This is  "Model number XO Learning tablet".  Android version 4.4.2.  Kernel version 3.4.67.  Build number ALPS.KK1.MP10.V1.8.  

> Your home directory is on the sdcard, but is at /sdcard/GNURoot/home ...

/sdcard/GNURoot/home is non-existent.

/storage/emulated/legacy/GNURoot/home is in the internal storage.
/storage/sdcard/home is in the external microSD card.

Appears this system imposes a "Default write disk" which  
must be either "USB storage" or "SD card".  This artificial 
separation doesn't exist in any other Linux I've ever seen.
It's a nuisance but not imposed by GNURoot Debian.

FWIIW, home in the internal storage is interesting but 
has limited practical utility.  home in the external microSD 
would have good practical utility.  Impossible with GNURoot 
Debian installed internally?

Thanks,                  ... Peter E.

**Comment by wacsyweezy** [comment]
I have been wondering how i can access my device inbuilt storage, but this post help me. My device storage files/folders are all in the sdcard folder. 

Thanks Corbin.

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by LutzHas** [comment]
The issue is long solved.
I should have closed it myself.
Sorry.

**Comment by peasthope** [comment]
LutzHas> The issue is long solved.

How?  Ie., how is the external SD card addressed?  Is this answered in documentation?

Issue 253 is also concerned with access to the external SD card.  According to 
AdamMatthewLTN at 2018-05-07 there are "... significant number of issues specifically regarding directories ...".  

Thanks,                                          ... Peter E.
