### ISSUE TITLE
Chown doesn't print error message when attempting to change ownership of a file illegally.

### ISSUE THREAD

**Issue by MatthewTighe** [corbinlc/GNURootDebian#137]
If file `a` is owned by root and "user" calls

`chown 1000:1000 a` no error message will be printed even though ownership of the file (correctly) is not changed.

Running proot version prior to L2S fix for hosed fd paths.

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam
