### ISSUE TITLE
Crash On Launch | Priv | 6.0.1

### ISSUE THREAD

**Issue by Kyrluckechuck** [corbinlc/GNURootDebian#146]
Been trying to get this app to launch but having no such luck. The initial install went okay it seems with the command line flooding of files it unpacked, but after it finish it crashed and showed 'Window 1' in a gray floating bar briefly on my home screen. Would try to relaunch the app, but the same thing happens. No dice after trying reboot either.

It's always the same, shows the terminal with some blue text for a brief second, then crashes to home screen

Let me know if there's any more information I can provide!

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by Kyrluckechuck** [comment]
I don't have the device with the same version as this is reported for, so I'll close it for you - -  it may still be an issue
