### ISSUE TITLE
Filesystem issue when trying to git clone

### ISSUE THREAD

**Issue by SnarkBoojum** [corbinlc/GNURootDebian#158]
Hi,

here is what I get when I try to git clone a work repository:
     error: unable to write sha1 filename /home/jpuydt/Enseignement/2016-2017/.git/objects/pack/pack-c010def3d34041a8889fb30ea086c1a6dc166f3c.pack: No such file or directory
     fatal: cannot store pack file
     fatal: index-pack failed

How can I solve this?

**Comment by SnarkBoojum** [comment]
Ah, I tried in /root as root, and it worked -- that might be a clue!

**Comment by corbinlc** [comment]
What version of GNURoot Debian are you using?  This sounds exactly like an issue solved a couple of versions back.

**Comment by SnarkBoojum** [comment]
I'm using the latest available on the google playstore.

**Comment by corbinlc** [comment]
Can you humor me and provide the version number per what you see in your applications manager on your device?

Can you provide the commands to start from a clean install to replicating this error?

**Comment by SnarkBoojum** [comment]
Sigh... I don't have a clean install anymore : I have already updated the app quite a few times...

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by SnarkBoojum** [comment]
I just tried to git clone a repository within GNURoot Debian, and there was no problem : closing!

Thanks!
