### ISSUE TITLE
How much space does GNURoot Debian take up?

### ISSUE THREAD

**Issue by whit3bear** [corbinlc/GNURootDebian#160]
Hey, I was just wondering how much space would be needed for the GNURoot filesystem.
I don't currently own a Android phone, but I'm going to buy one and I'm debating whether to get a 32GB or 64GB phone, depending on how much space GNURoot eats up.
Thanks in advance. :)

**Comment by Root-voidX** [comment]
In the begining it uses maybe 14 to 20 mb. When you load packages it gets bigger. So depending on the package sizes. A DE like lxde can take more than a gb of space. I am using almost 5GB with a lxde de, octave,scilab,paraviee,blender,ccx,foam etc. So yah.

**Comment by WHIT3BEAR** [comment]
Hey, thank you.
That's not so bad! Well, @Root-voidX, do you recommend any good, cheap Android phones?
(I was checking out the OnePlus 3T but they don't have any official stores where I'm at and I'm not so sure about warranty...)

**Comment by Root-voidX** [comment]
Depends on where you are from! I suggest trying to get last years flagship for cheap, but if you worry about warenty, then try for a axon 7 or the new hauwei midrange. Kirin 960 is a beast soc with the latest cortex A73. Helps alot for foam or number crunching. But gui is hard to come by 👀

**Comment by whit3bear** [comment]
I'm in Thailand. No official stores here...
Thanks for the recommendations! I'll check them out.
:)

**Comment by whit3bear** [comment]
Say, if I was to get a OnePlus 3T at an unofficial store, with good reviews (people say it is good and the phones there have a one year warranty. Cost a bit more as well), would that be risky?

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by whit3bear** [comment]
Hey Adam,
the problem is resolved. I apologize for the late reply and for not closing this issue.
