### ISSUE TITLE
Can I install rootfs on sd card?

### ISSUE THREAD

**Issue by souravndp** [corbinlc/GNURootDebian#167]
I have a very old mobile (GT-S5360) and I want to install Debian text-only on it. It has very low internal memory (about 150 MB). I tried to install Debian wheezy but failed. the popup "unpacking a rootfs this may take some time" closes after some time but no rootfs is created. I think this is because of no storage space left. I have successfully installed aboriginal and it takes about 80 MB on my internal memory card. So, Debian will take more space, I think. So, I was asking, can it be installed on the sd card?

**Comment by TheNeoBurn** [comment]
Hej, I've done this myself just yesterday. You'll need a rooted device (otherwise the following is not permitted), format you sd card with ext2 (fat doesn't support the required rights management), mount the sd card manually, create a folder to store the Linux files on the sd card, delete the "debian" folder in the app's data folder (/data/data/com.gnuroot.debian/debian), create a symlink to the sd card folder instead (ln -s /path/to/your/debian /data/data/com.gnuroot.debian/debian) and restart the app. It'll reinstall everything on sd card if everything went fine. I haven't managed to automatically mount the sd card on boot yet but I advise to do so.

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by souravndp** [comment]
I currently don't have a mobile device with external SD card. So, I can't verify if the issue is still relevant. But, this issue should not be a high priority because nowadays most mobiles have enough internal memory. The device I used is from 2011.

I am closing the issue. But just a low priority feature request: Please make an option in settings which will allow downloading the image/required files on sd card instead of internal memory.
