### ISSUE TITLE
-su: ./factorio: Permission denied

### ISSUE THREAD

**Issue by IIPoliII** [corbinlc/GNURootDebian#185]
Hello!

I get this error every time i try to launch a script what could i do my error ;

`root@localhost:/home/factorio/factorio/bin/x64`
`chmod +x factorio`
`root@localhost:/home/factorio/factorio/bin/x64`
`./factorio`
`-su: ./factorio: Permission denied`

Thanks for helping.

**Comment by casept** [comment]
What CPU architecture does your phone have? Factorio only support amd64 (and ost phones are armhf or aarch64). Also, factorio probably requires "real" OpenGL, not the stripped down one on Android. Even if you managed to solve this error you're probably not going to get it to run, sorry.

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam
