### ISSUE TITLE
External Wifi Adapter connection

### ISSUE THREAD

**Issue by mirzaatifbaig** [corbinlc/GNURootDebian#194]
I've been Using It for ages And Now I've Got A Question.Is it Possible for us to connect An External Wifi adapter to the Chrooted(or prooted) Environment?I might seem crazy but another one that Is It possible to Use My mobile's internal adapter .And By The Way Loved YouR WORK.Nice One.

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by mirzaatifbaig** [comment]
Hi.Update:I was being a Jackass and the Issue was related to my Own Kernel.So,I built a kernel based on leankernel but that was messy.At the end I heard about this Kali on android Thingy called nethunter kernel.Which worked out damn Well on both chroot and  official kali setup.Thanks for Creating Such an amzing app.

**Comment by mirzaatifbaig** [comment]
Hi.Update:I was being a Jackass and the Issue was related to my Own Kernel.So,I built a kernel based on leankernel but that was messy.At the end I heard about this Kali on android Thingy called nethunter kernel.Which worked out damn Well on both chroot and  official kali setup.Thanks for Creating Such an amzing app.
