### ISSUE TITLE
[Query] Running process from outside the box

### ISSUE THREAD

**Issue by the-maux** [corbinlc/GNURootDebian#203]
Hi, 

First, amazing work, really.

I don't have an issue to report, just a question.

Is that possible to communicate with a shell inside GNURootDebian from a shell outside the GNURootDebian fs ?
I tryied (on other many thing, like './ExecInProot [..] bash' who return Permission Denied) to manage the fd's of the process by the /proc/pidOfShellInGNURootDebian/fd but no real success so far.
The ssh/dropbear solution could work, but takes really to much time for the kind of conception i need.

My goal is to be able to execute some binary in the /bin of the GNURootDebian fs.

Thanks in advance.

**Comment by coax75ohm** [comment]
If ssh has too much latency, you could try something with less overhead like netcat. Granted you'll probably need to do a bit of scripting to set it up.

Do to the way Android sandboxes apps I don't think there's any other way than a network socket or a rooted install.

**Comment by the-maux** [comment]
I tryid the netcat process but unsuccessful so far.
I'm on a rooted device with custom rom btw, is there some more possibility with ?
I was more thinking about an unix mecanism, like a duplicate fd from the bash process inside the proot ?
Thanks

**Comment by coax75ohm** [comment]
Sounds like you need something like [Debian Kit](https://sourceforge.net/projects/debian-kit/) which does a side-by-side install, rather than proot/chroot. I haven't used it in years and it doesn't look like it's been maintained unfortunately.

Another project for rooted devices is [Linux Deploy](https://github.com/meefik/linuxdeploy), which works well if you can get past the interface and utter lack of documentation.

**Comment by the-maux** [comment]
Debian Kit is awesome but the device i'm working with is not supported because of the SELinux unpermissive still protected by KNOX.
I will give a try with Linux Deploy, Thanks a lot!
