### ISSUE TITLE
Making utime work?

### ISSUE THREAD

**Issue by peterwilli** [corbinlc/GNURootDebian#205]
Hello there,

Currently I installed Debian Chroot on my new chromebook. This works well other than the fact that unzipping tar or zip archives leads to a bunch of cryptic errors which I was told I could ignore. While the archive still unpacks, some tools like npm are checking the output for errors and then decide based on those errors to stop.

Can we somehow ignore this kind of call? Thanks!
![screenshot 2017-09-02 at 00 48 37](https://user-images.githubusercontent.com/1212814/29990208-c66d90cc-8f78-11e7-9ad0-0d49405b2e86.png)

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by peterwilli** [comment]
Hi there, I haven't tried it anymore. I'm still using a Chromebook for on-the-go dev work but I started using Crouton (I know developer mode is less secure, but Crouton makes some effort in securing things up again like re-enabling bootloader signature checks)

But in general, I think the issue is less relevant, especially since Google themselves is implementing Linux containers natively in ChromeOS.
