### ISSUE TITLE
Failed to open display

### ISSUE THREAD

**Issue by abinashdash17** [corbinlc/GNURootDebian#235]
XSDL server is running in background. Still i'm getting this error even after exporting display.

root@localhost:/# export DISPLAY=:0
root@localhost:/# startlxde
** Message: main.vala:99: Session is LXDE
** Message: main.vala:100: DE is LXDE

(lxsession:11908): Gtk-WARNING **: cannot open display: :0

How can i fix this?

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by abinashdash17** [comment]
This is not a GNUrootdebian issue. Some firewall was blocking outgoing connection on loopback network. I wasn't able to disable the firewall but I fixed this issue by creating a new loopback network in my rooted mobile. Now XSDL and gnurootDebian is working fine.

**Comment by corbinlc** [comment]
Great to hear things are working for you.  Keep filing issues as we are
very engaged in this project again.
