### ISSUE TITLE
Keyboard settings - chrome os

### ISSUE THREAD

**Issue by Lucaacer** [corbinlc/GNURootDebian#240]
I am running GnuRootDebian on a chromebook. My keyboard is qwertz, but it's set to qwerty IT and everything works in chrome OS (I am mainly a touch typist and I know the IT layout).

When I type inside the Prooted environment instead, there is no way to use the qwerty IT config, it stays on qwerty US, so I have to switch to the US layout even in chrome OS, for the settings to match. If I don't, several keys are all over (not US, not IT, not DE... IDK).

I tried every debian known solution dpkg reconfigure etc., with no avail. It looks there is something preset somewhere.

Has anyone faced and solved this issue?

Thanks.

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam

**Comment by Lucaacer** [comment]
Sorry, I haven't been here for some days.

Yes, the issue is still here, even after powerwashing my device and install GNUroot from scratch. It is neither related to the desktop applied, nor to the windows manager. I tried a workaround, see here https://nolirium.blogspot.it/2018/02/modifying-hardware-key-layouts-for.html but it does not work without developer's mode and the main purpose of GNUroot just resides in avoiding such mode.

Btw, I have also been looking for a way to be able to copy and paste from Chrome OS to GNUroot clipboard (so as you can do with Crouton) but there is no way without developer's mode. Someone should upload a chrome extension to the chrome web store that automatically saves clipboard content to Download folder and then I could easily make a script inside GNUroot that could import such txt file to GNUroot clipboard.

Thanks!

**Comment by Lucaacer** [comment]
Thanks.

To be honest, while GNUroot is a great option for any unrooted android phone,  the upcoming project Crostini should deliver full GNU linux support, GUI incliuded, to most chromebook, so maybe it's not worth spending a lot of time to solve these bugs. Most chromebooks are sold in the USA and they use the USA layout, so they won't even face this bug..
