### ISSUE TITLE
`apt-utils` error after last update

### ISSUE THREAD

**Issue by Andre0991** [corbinlc/GNURootDebian#43]
Hi. 

After the last update, when I try to install any package with `apt-get install`, I get an error:

``` bash
root@localhost:/# apt-get install git

# etc

debconf: delaying package configuration, since apt-utils is not installed
apt-get: ../sysdeps/unix/grantpt.c:236: grantpt: Assertion `! "getpt: internal error: invalid exit code from pt_chown"' failed.
Aborted
```

Thanks.

My system:
Nexus 4
Android 5.1.1

**Comment by davidmegginson** [comment]
Also spotted on Nexus 7 (2013) running 5.1.1. Tried several combinations of steps from new images, but always the same result.

My Nexus 6 (also running 5.1.1) throws up some warnings, but *does* allow me to install new software with apt-get

**Comment by corbinlc** [comment]
Having a miserable time with PRoot and the last couple of version of Android.  6.0 stopped supporting hard links, so I had to get a PRoot extension that replaces hard links with soft links working.  Obviously this doesn't work for all devices running 5.1.  Sadly it did work for the device I had running 5.1.  Ugh!  I will debug, but firstly, I will back out the change of PRoot for devices that don't need it.  Need to get list of beta testers going because I cannot test all versions of android and all devices.

**Comment by davidmegginson** [comment]
Happy to help test, but I'm travelling for meetings this week, so I might need a day or so to get back with results. Thanks for the quick reply!

**Comment by Andre0991** [comment]
Thanks for you answer.

Add me to the list of beta testers :)

**Comment by corbinlc** [comment]
I pushed new beta APKs to the market.  It will take up to 2 hours for those to be available to you.  
This new FAQ page talks about how to become a beta tester:
http://corbinlc.github.io/GNURootDebian/
Sign up to become a better tester by joining the Google Plus Community linked there.  And update to the new version.  After I get a little feedback, I will push it to production.

**Comment by Andre0991** [comment]
Cool, I sent a join request.
