### ISSUE TITLE
Any way to turn selinux off?

### ISSUE THREAD

**Issue by davidgiven** [corbinlc/GNURootDebian#49]
I'm finding that a number of things don't work because they're trying to talk to selinux. But the visible version of selinux is Android's real one, which thinks we're running as a user, rather than a fake one, or even a non-present one.

This produces errors when installing things like mime-support:

```
dpkg (subprocess): cannot set security execution context for maintainer script: Permission denied
```

or:

Is there a way to pretend to the chroot that selinux is not present at all?

**Comment by corbinlc** [comment]
Works for me, but I have also made improvements to GNURoot Debian since you filed this.  Can you try again?

Were you possibly using GNURoot instead of GNURoot Debian?  Or were you possibly SSHing in?  There were problems with both of these cases related to selinux, but that has been solved.

So, specifically use GNURoot Debian and update it to the latest and hit the patch button and then try this again.

Tell me how it goes.
