### ISSUE TITLE
Dropbear and sshd do not run

### ISSUE THREAD

**Issue by jiang-qian** [corbinlc/GNURootDebian#52]
dropbear or sshd installed with apt-get cannot be initialized: invoke-rc.d failed to start the daemon.
Thus it is currently not possible to run any ssh daemon such that one can ssh into the chroot environment.

**Comment by cercata** [comment]
Yo hace to set the port to semethong bigger than 1024.
The default 22 port is reserved by android:

https://github.com/corbinlc/GNURootDebian/issues/53

**Comment by corbinlc** [comment]
@cercata is correct

Here are more instructions about getting setup with an ssh server.

Try the new version of GNURoot Debian. You just need to hit the "Patch" button after updating.

1) You need a user with a password set.
1a) If you plan to login via ssh as "root" use passwd to set a password
1b) If you plan to login via ssh as some other user, use adduser to create a new user and assign it a password.

2) You need to get a ssh server running
apt-get update
apt-get install dropbear
The installation of the package will also start the server, but you can manually start the server later.

3) Connect to the server
3a) From inside GNURoot Debian - in another terminal use dbclient (installed as part of dropbear) to connect. You just need to connect to root@localhost or myusername@localhost if you create a non-root user.
3b) From outside GNURoot Debian - in JuiceSSH app or from anywhere else, connect in the normal fashion, but connect to port 2022 instead of the default 22.
The reason for adding 2000 to the port number if that ports < 1024 are reserved and not usable by apps on android, so GNURoot Debian has a new PRoot extension that adds 2000 to the port number used when starting a server if the original port number is < 1024.

Using openssh is a little more complicated, so please use dropbear if possible.

Please comment as to whether this works for you.
