### ISSUE TITLE
Server refused to allocate pty

### ISSUE THREAD

**Issue by peter279k** [corbinlc/GNURootDebian#72]
I used GNURootDebian and installed dropbear.It is a ssh server.
When I used putty to connect my ssh server, I got the error message: Server refused to allocate pty.
I referenced this [post's comment ](https://miracoin.wordpress.com/2014/05/28/installation-of-ssh-server-for-debian-in-android-gnuroot/) and I found where the problem was.
Is it possible to be fixed ? Thanks.

**Comment by cercata** [comment]
Duplicated:

https://github.com/corbinlc/GNURootDebian/issues/53

**Comment by corbinlc** [comment]
Try the new version of GNURoot Debian.  You just need to hit the "Patch" button after updating.  

1) You need a user with a password set.
1a) If you plan to login via ssh as "root" use passwd to set a password
1b) If you plan to login via ssh as some other user, use adduser to create a new user and assign it a password.

2) You need to get a ssh server running
apt-get update
apt-get install dropbear
The installation of the package will also start the server, but you can manually start the server later.

3) Connect to the server
3a) From inside GNURoot Debian - in another terminal use dbclient (installed as part of dropbear) to connect.  You just need to connect to root@localhost or myusername@localhost if you create a non-root user.
3b) From outside GNURoot Debian - in JuiceSSH app or from anywhere else, connect in the normal fashion, but connect to port 2022 instead of the default 22.
The reason for adding 2000 to the port number if that ports < 1024 are reserved and not usable by apps on android, so GNURoot Debian has a new PRoot extension that adds 2000 to the port number used when starting a server if the original port number is < 1024.

Using openssh is a little more complicated, so please use dropbear if possible.

Please comment as to whether this works for you.

**Comment by cercata** [comment]
Nice, now dropbear works "ouit-of-the-box", and you can use putty with it.

Great work.

**Comment by peter279k** [comment]
Hi @corbinlc . Thank you for your comment. Finally, I tried to use patch button and it worked successfully.

**Comment by bufaird** [comment]
Hi, 
  I'm having similar problems with Gnuroot Gentoo.

  Any chance of updating that?

**Comment by peter279k** [comment]
I finally use the patch button to solve my problem in my research and I have never used Gentoo before.
Maybe I check that at my available time.

**Comment by bufaird** [comment]
Gentoo throws serious problems when you try to execute "df - h".
