### ISSUE TITLE
SSH dropbear /openssh-server dropping connection

### ISSUE THREAD

**Issue by kdulep** [corbinlc/GNURootDebian#77]
when you connect from ssh client server resets connection dropbear/openssh-server
port >1024

**Comment by cercata** [comment]
Can yo give more details ...

Maybe this is your problem, still not fixed:
https://github.com/corbinlc/GNURootDebian/issues/53

**Comment by corbinlc** [comment]
Try the new version of GNURoot Debian.  You just need to hit the "Patch" button after updating.  

1) You need a user with a password set.
1a) If you plan to login via ssh as "root" use passwd to set a password
1b) If you plan to login via ssh as some other user, use adduser to create a new user and assign it a password.

2) You need to get a ssh server running
apt-get update
apt-get install dropbear
The installation of the package will also start the server, but you can manually start the server later.

3) Connect to the server
3a) From inside GNURoot Debian - in another terminal use dbclient (installed as part of dropbear) to connect.  You just need to connect to root@localhost or myusername@localhost if you create a non-root user.
3b) From outside GNURoot Debian - in JuiceSSH app or from anywhere else, connect in the normal fashion, but connect to port 2022 instead of the default 22.
The reason for adding 2000 to the port number if that ports < 1024 are reserved and not usable by apps on android, so GNURoot Debian has a new PRoot extension that adds 2000 to the port number used when starting a server if the original port number is < 1024.

Please comment as to whether this works for you.
