### ISSUE TITLE
su - <user> can't find home directory

### ISSUE THREAD

**Issue by y-salnikov** [corbinlc/GNURootDebian#9]
New user can't login with default home directory /home/<username>. Is it possible to add default user to GUI? It's not a good practis to work with root in linux, even it is fake root.

**Comment by AdamMatthewLTM** [comment]
Hi all,

I am currently assisting the developers in sorting relevant issues for GNURoot Debian on GitHub. If the issue discussed is still relevant, could you please reply to this thread and state the issue needs to be resolved and I will attempt to sort it for you ASAP. If the issue is no longer relevant, please reply to this thread and state it has been resolved, and I will suggest this thread be closed.

Furthermore, if a particular issue is considered to be high priority, please state that you are requesting it to be considered as high priority and I will mark it as such.

Thank you all so much for your time and understanding,
-Adam
